spring.application.name=chatt-backend
server.port=${PORT:8082}

frontend.url=http://localhost:5173
spring.data.mongodb.uri=mongodb://localhost:27017/chatapp

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration