spring.application.name=chatt-backend
server.port=${PORT:53211}

frontend.url=http://localhost:5179
//spring.data.mongodb.uri=mongodb://localhost:27017/chatapp

spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration

spring.data.mongodb.uri=mongodb+srv://utkarsh_db_user:9415812823@cluster0.s3jjr6.mongodb.net/chatapp?appName=Cluster0